# Configurations
```{r}
library(Seurat)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(cowplot)
library(stringr)
library(tidyverse)
library(ggalluvial)
```
```{r}
neurons <- readRDS("/projects/perslab/people/jmg776/projects/DVC/output/Seurat_objs/integrated/neurons_Seurat_obj_labels.rds")
glia <- readRDS("/projects/perslab/people/jmg776/projects/DVC/output/Seurat_objs/integrated/glia_Seurat_obj.rds")
cellex_macaque <- read.table(gzfile("/projects/perslab/people/jmg776/projects/DVC/output/CELLEX/output/macaque_DVC_neurons_mm.esmu.csv.gz"), header = T, sep = ",", row.names = 1)
cellex_mouse <- read.table(gzfile("/projects/perslab/people/jmg776/projects/DVC/output/CELLEX/output/mouse_DVC_neurons_mm.esmu.csv.gz"), header = T, sep = ",", row.names = 1)
cellex_rat <- read.table(gzfile("/projects/perslab/people/jmg776/projects/DVC/output/CELLEX/output/rat_DVC_neurons_mm.esmu.csv.gz"), header = T, sep = ",", row.names = 1)
ludwig2021_neurons <- readRDS("/projects/perslab/people/jmg776/projects/DVC/output/Seurat_objs/mouse/mouse_neurons_Ludwig_reintegrated_Seurat_obj.rds")

neurons$cell.type <- gsub("_(\\d+)_", "\\1.", neurons$cell.type)
colnames(cellex_mouse) <- gsub("_(\\d+)_", "\\1.", colnames(cellex_mouse))
colnames(cellex_rat) <- gsub("_(\\d+)_", "\\1.", colnames(cellex_rat))
colnames(cellex_macaque) <- gsub("_(\\d+)_", "\\1.", colnames(cellex_macaque))
glia$cell.type <- gsub("_", " ", glia$cell.type)
```


# 3a. Dot plot, key genes
```{r}
##############
### Format ###
##############

format_species <- function(data, species_name) {
  expr <- data[genes, ]
  expr$gene <- rownames(expr)
  expr <- reshape2::melt(expr, id.vars = "gene")
  colnames(expr) <- c("gene", "celltype", "cellex_score")
  expr$species <- species_name
  return(expr)
}

# Define genes of interest
genes <- c("Calcr", "Ramp3")

# Format data for each species
mouse_data <- format_species(cellex_mouse, "mouse")
rat_data <- format_species(cellex_rat, "rat")
macaque_data <- format_species(cellex_macaque, "macaque")
species_data <- rbind(mouse_data, rat_data, macaque_data) %>% filter(gene %in% genes)

# Adjust factor levels to ensure the desired plotting order
species_data$species <- factor(species_data$species, levels = c("macaque", "rat", "mouse"))  # Put mouse last for the plot
species_data$celltype <- factor(species_data$celltype, levels = levels(factor(neurons$cell.type)))
species_data$gene <- factor(species_data$gene, levels = rev(genes))

# Adjust the color column with correct factor levels
species_data$color <- factor(paste0(species_data$species, round(species_data$cellex_score * 100, 0)),
                             levels = c(paste0("mouse", seq(0, 100)),
                                        paste0("rat", seq(0, 100)), 
                                        paste0("macaque", seq(0, 100))))

# Define color palettes for each species with named colors
palettes <- unlist(list(
  mouse = setNames(colorRampPalette(c("#C2BEC0", "#8AC1B6", "#46D3B8"))(101), paste0("mouse", 0:100)),
  rat = setNames(colorRampPalette(c("#C2BEC0", "#819bb7", "#546577"))(101), paste0("rat", 0:100)),
  macaque = setNames(colorRampPalette(c("#C2BEC0", "#F0A572", "#E8682F"))(101), paste0("macaque", 0:100))
))
names(palettes) <- sub("^[^.]+\\.", "", names(palettes))

# Create heatmaps for each gene
for (i in seq_along(genes)) {
  gene <- genes[i]
  
  heatmap_plot <- ggplot(
    subset(species_data[species_data$gene == gene & species_data$celltype %in% c("Glu0.2", "Glu2.1", "Glu2.2", "Glu5.2", "Glu6.0", "Glu6.2"),]), 
    aes(x = celltype, y = species, color = color)
  ) +        
    geom_tile(size = 2, color = "white", fill = "grey99") +
    geom_point(size = 2.5, stroke = 0) +
    scale_color_manual(values = palettes) +
    scale_x_discrete(expand = c(0, 0)) +
    xlab(NULL) + ylab(gene) +
    theme(
      axis.text.y = element_blank(), 
      axis.title.y = element_text(size = 6, face = "bold.italic", angle = 360, vjust = 0.5),
      legend.position = "none",
      axis.line = element_line(colour = "black", size = 0.4),
      axis.ticks = element_blank(),
      plot.margin = unit(c(0, 0.1, 0.1, 0.1), "cm"),
      panel.spacing = unit(0.1, "cm"),
      panel.background = element_blank(),
      panel.grid.minor = element_blank(),
      axis.text.x = element_blank()
    )
  
  assign(paste0("heatmap_plot", i), heatmap_plot)
}
```
```{r}
############
### Plot ###
############

draw_gradient <- function(palette, species_name) {
  species_palette <- palette[grep(species_name, names(palette))]  # Extract only the relevant portion of the palette for the species
  species_title <- paste(str_to_title(species_name), "ESμ")

  ggplot(data.frame("x" = seq_along(species_palette),
                    color = factor(names(species_palette), levels = names(species_palette))),
         aes(x = x, y = 1, fill = color)) +
    geom_tile(show.legend = FALSE) +
    scale_fill_manual(values = species_palette) +
    theme_void() +
    ggtitle(species_title) +
    scale_x_continuous(breaks = seq(0, 100, by = 25),
                       labels = seq(0, 1, by = 0.25)) +
    theme(axis.text.x = element_text(size = 6, face = "bold"),
          plot.title = element_text(hjust = 0.5, size = 6, face = "bold"))
}

labels_plot <- ggplot(data.frame(celltype = factor(c("Glu0.2", "Glu2.1", "Glu2.2", "Glu5.2", "Glu6.0", "Glu6.2"))), 
                      aes(x = celltype, y = 1)) +
  geom_blank() +
  theme_void() +
  theme(axis.text.x = element_text(size = 10, face = "bold", angle = 45, hjust = 1),
        axis.ticks.x = element_line()) +
  xlab("")

legend_plot <- plot_grid(
  draw_gradient(palettes, "mouse"), 
  draw_gradient(palettes, "rat"), 
  draw_gradient(palettes, "macaque"), 
  ncol = 1
)

p <- plot_grid(legend_plot,
               heatmap_plot1, heatmap_plot2,
               labels_plot, 
               align = "v", 
               ncol = 1)

p

ggsave("/projects/perslab/people/jmg776/projects/DVC/figures/figure_3a.pdf", height = 8, width = 10)
```

# 3e. Sankey diagram
```{r}
##############
### Format ###
##############

ludwig2021_neurons <- subset(ludwig2021_neurons, cells = which(colnames(ludwig2021_neurons) %in% gsub("_[0-9]+$", "", colnames(neurons)[which(neurons$year == "2021")])))
neurons$ludwig.celltype <- NA
neurons$ludwig.celltype[na.omit(match(colnames(ludwig2021_neurons), gsub("_[0-9]+$", "", colnames(neurons))))] <- ludwig2021_neurons$cell.subtype2

celltype_data <- subset(
  data.frame(
    celltype = neurons$cell.type[neurons$dataset == "mouse.2021"],
    ludwig_celltype = neurons$ludwig.celltype[neurons$dataset == "mouse.2021"]),
  !is.na(ludwig_celltype))

for (ludwig_type in unique(celltype_data$ludwig_celltype)) {
  freq_table <- as.data.frame(table(celltype_data$celltype[celltype_data$ludwig_celltype == ludwig_type]))  # Check how many of present dataset map to current Ludwig2021 cell type
  unmappable <- freq_table$Var1[freq_table$Freq < (sum(freq_table$Freq) * 0.2)]  # If less than 20% of a given cell type map to Ludwig2021, it will be considered unmapped
  
  celltype_data$ludwig_celltype[celltype_data$celltype %in% unmappable & celltype_data$ludwig_celltype == ludwig_type] <- "unmapped"
}
```
```{r}
############
### Plot ###
############

counts <- celltype_data %>%  # Aggregate counts for plotting
  group_by(celltype, ludwig_celltype) %>%
  summarise(Freq = n(), .groups = 'drop') %>%
  filter(celltype %in% c("Glu0.2", "Glu2.1", "Glu2.2", "Glu5.2", "Glu6.0", "Glu6.2"))  # Only interested in subset

p <- ggplot(counts, aes(axis1 = celltype, axis2 = ludwig_celltype, y = Freq)) +
  geom_alluvium(aes(fill = celltype), width = 1/12) +
  geom_stratum(width = 1/12, fill = "grey", color = "black") +
  geom_text(
    stat = "stratum",
    aes(label = after_stat(stratum),
      x = after_stat(x) + 0.1 * ifelse(after_stat(x) == 1, -1, 1),
      hjust = ifelse(after_stat(x) == 1, 1, 0)),
      size = 3) +
  scale_x_discrete(limits = c("Present", "Ludwig et. al 2021")) +
  theme_minimal() +
  theme(legend.position = "none",
    axis.title = element_blank(),
    axis.text.x = element_text(size = 12),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    panel.grid = element_blank(),
    plot.title = element_blank())

p

ggsave("/projects/perslab/people/jmg776/projects/DVC/figures/figure_3e.pdf", height = 4, width = 5)
```

